class Config:
    DATA_BASE_DIR: str = "./data/images"
    CLASS_MAP = {
        0: "aerosol cans",
        1: "aluminum food_cans",
        2: "aluminum soda cans",
        3: "cardboard boxes",
        4: "cardboard packaging",
        5: "clothing",
        6: "coffee grounds",
        7: "disposable plastic cutlery",
        8: "eggshells",
        9: "food waste",
        10: "glass beverage bottles",
        11: "glass cosmetic containers",
        12: "glass food jars",
        13: "magazines",
        14: "newspaper",
        15: "office paper",
        16: "paper cups",
        17: "plastic cup lids",
        18: "plastic detergent bottles",
        19: "plastic food containers",
        20: "plastic shopping bags",
        21: "plastic soda bottles",
        22: "plastic straws",
        23: "plastic trash bags",
        24: "plastic water bottles",
        25: "shoes",
        26: "steel food cans",
        27: "styrofoam cups",
        28: "styrofoam food containers",
        29: "tea bags",
    }
